### ISSUE TITLE
is their any pretrained model ?

### ISSUE THREAD

**Issue by AhmadNashaat0** [neoglez/neural-anthropometer#1]

**Comment by neoglez** [comment]
Not at the moment. But I plan to integrate it soon.

- [x] Add pretrained model.

**Comment by neoglez** [comment]
I added a [pretrained model](https://github.com/neoglez/neural-anthropometer/blob/main/model/Neural_Anthropometer_Model_17-03-2021_08-26-53_fold-4.pt) and a [notebook](https://github.com/neoglez/neural-anthropometer/blob/main/notebook/inference_neural_anthropometer.ipynb) showing how to perform inference.
